import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { Amplify } from "aws-amplify";
// Import the dynamic file generated by your CDK deploy
import cdkExports from "./cdk-exports.json";

// 1. SAFE EXTRACTION: Cast to 'any' to avoid TypeScript "property not found" errors
const config = (cdkExports as any)["AwsCognitoAuthStack"];

if (!config) {
  console.error("Error: Could not find 'AwsCognitoAuthStack' in cdk-exports.json");
}

Amplify.configure({
  Auth: {
    Cognito: {
      userPoolId: config.UserPoolId,
      userPoolClientId: config.UserPoolClientId,
      identityPoolId: config.IdentityPoolId,
      loginWith: {
        email: true,
        // Inside Amplify.configure
      oauth: {
        // CORRECT: Just the text, no https://
        domain: "auth-app-vedantyeola-2026-test.auth.ap-south-1.amazoncognito.com", 
        scopes: ["openid", "email", "profile"], 
        // CORRECT: This is where Cognito sends the user back to YOU
        redirectSignIn: ["http://localhost:3000/"], 
        redirectSignOut: ["http://localhost:3000/"],
        responseType: "code"
      }
      },
    },
  },
  Storage: {
    S3: {
      bucket: config.BucketName,
      region: "ap-south-1",
    },
  },
});

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);